services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs-backend-dev
    restart: always
    command: npm run start:dev
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./backend:/usr/src/app
      - ./backend/prisma:/usr/src/app/prisma
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    ports:
      - "${API_PORT}:${API_PORT}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-frontend-dev
    restart: always
    command: npm run dev
    environment:
      EXTERNAL_API_URL: ${EXTERNAL_API_URL}
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    ports:
      - "${FE_PORT}:${FE_PORT}"

volumes:
  pgdata:
